import hashlib
import mimetypes
from pathlib import PurePath
from typing import Any

from core.config import load_config
from core.config.logging import Logger
from core.database.release_db import ReleaseDatabase


REQUIRED_FILES = {"install.ps1", "git-ai-windows-x64.exe"}
DEFAULT_CHANNELS = ["latest", "next", "enterprise-latest", "enterprise-next"]


class ReleaseValidationError(ValueError):
    pass


class ReleaseService:
    def __init__(
        self,
        database: ReleaseDatabase | None = None,
        config: dict[str, Any] | None = None,
    ):
        self.logger = Logger.get_logger("services.release")
        releases_config = (
            config if config is not None else load_config().get("git_ai", {}).get("releases", {})
        )
        self.database = database or ReleaseDatabase()
        self.max_file_size = int(releases_config.get("max_file_size_mb", 200)) * 1024 * 1024
        self.max_files = int(releases_config.get("max_files_per_release", 12))
        self.allowed_channels = releases_config.get("allowed_channels", DEFAULT_CHANNELS)

    def create_release(
        self,
        *,
        tag: str,
        version: str | None,
        channel: str,
        description: str | None,
        created_by: str | None,
        files: list[Any],
    ) -> dict[str, Any]:
        tag = tag.strip()
        version = (version or tag).strip()
        channel = channel.strip()
        if not tag:
            raise ReleaseValidationError("tag is required")
        if channel not in self.allowed_channels:
            raise ReleaseValidationError(f"channel {channel} is not allowed")
        if len(files) > self.max_files:
            raise ReleaseValidationError(f"too many files, maximum {self.max_files}")

        artifacts = [self._read_upload_file(file) for file in files]
        names = {artifact["filename"] for artifact in artifacts}
        if "SHA256SUMS" in names:
            raise ReleaseValidationError("SHA256SUMS is generated by server")
        missing = sorted(REQUIRED_FILES - names)
        if missing:
            raise ReleaseValidationError(f"missing required files: {', '.join(missing)}")
        checksums_artifact = self._build_sha256sums_artifact(artifacts)
        artifacts.append(checksums_artifact)

        return self.database.create_release(
            tag=tag,
            version=version,
            channel=channel,
            sha256sums_checksum=checksums_artifact["sha256"],
            artifacts=artifacts,
            description=description,
            created_by=created_by,
        )

    def list_channel_metadata(self) -> dict[str, dict[str, str]]:
        channels = {
            channel: {"tag": "", "version": "", "checksum": "", "platforms": []}
            for channel in DEFAULT_CHANNELS
        }
        for channel in channels:
            release = self.database.get_active_release(channel)
            if release:
                platforms = sorted(
                    {
                        artifact["platform"]
                        for artifact in self.database.list_artifacts(release["id"])
                        if artifact.get("platform")
                    }
                )
                channels[channel] = {
                    "tag": release["tag"],
                    "version": release["version"],
                    "checksum": release["sha256sums_checksum"],
                    "platforms": platforms,
                }
        return channels

    def get_active_artifact(self, channel: str, filename: str) -> dict[str, Any] | None:
        release = self.database.get_active_release(channel)
        if not release:
            return None
        return self.database.get_artifact(release["id"], filename)
    
    def get_version_artifact(self, version: str, filename: str) -> dict[str, Any] | None:
        release = self.database.get_release_by_version(version)
        if not release:
            return None
        return self.database.get_artifact(release["id"], filename)

    def _read_upload_file(self, file: Any) -> dict[str, Any]:
        filename = self._safe_filename(file.filename)
        content = file.read()
        if len(content) > self.max_file_size:
            raise ReleaseValidationError(f"{filename} exceeds max file size")
        sha256 = hashlib.sha256(content).hexdigest()
        return {
            "filename": filename,
            "artifact_type": self._artifact_type(filename),
            "platform": self._platform(filename),
            "sha256": sha256,
            "size_bytes": len(content),
            "content_type": file.content_type
            or mimetypes.guess_type(filename)[0]
            or "application/octet-stream",
            "content_blob": content,
        }

    def _build_sha256sums_artifact(self, artifacts: list[dict[str, Any]]) -> dict[str, Any]:
        lines = [
            f'{artifact["sha256"]}  {artifact["filename"]}'
            for artifact in sorted(artifacts, key=lambda item: item["filename"])
        ]
        content = ("\n".join(lines) + "\n").encode("utf-8")
        sha256 = hashlib.sha256(content).hexdigest()
        return {
            "filename": "SHA256SUMS",
            "artifact_type": "checksums",
            "platform": None,
            "sha256": sha256,
            "size_bytes": len(content),
            "content_type": "text/plain; charset=utf-8",
            "content_blob": content,
        }

    def _safe_filename(self, filename: str) -> str:
        name = PurePath(filename).name
        if not name or name != filename or "/" in filename or "\\" in filename:
            raise ReleaseValidationError(f"invalid filename: {filename}")
        return name

    def _artifact_type(self, filename: str) -> str:
        if filename.endswith(".sh") or filename.endswith(".ps1"):
            return "installer"
        return "binary"

    def _platform(self, filename: str) -> str | None:
        mapping = {
            "install.ps1": "windows-x64",
            "git-ai-windows-x64.exe": "windows-x64",
        }
        return mapping.get(filename)
